#######################################################################################################################
# Logging
#######################################################################################################################
logging:
  file: launchpad-api.log

#######################################################################################################################
# Spring Configuration
#######################################################################################################################
spring:

  application:
    name: Launchpad API

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/launchpad?useSSL=false&autoReconnect=true
    username: launchpad
    password: launchpad
    driver-class-name: com.mysql.jdbc.Driver
    #initialSize: 10
    #maxActive: 50
    #maxIdle: 30
    #maxWait: 100000
    #removeAbandoned: true
    #removeAbandonedTimeout: 60
    #logAbandoned: true
    #validationQuery: SELECT 1
    #testOnBorrow: true
    #testWhileIdle: true
    #testOnReturn: true
    #minEvictableIdleTimeMillis: 30000
    #timeBetweenEvictionRunsMillis: 30000

#######################################################################################################################
# Spring Boot Web / Embedded Tomcat
#######################################################################################################################
server:
  port: 8080
  contextPath: /api

#######################################################################################################################
# Spring Security
#######################################################################################################################
security:
  basic:
    enabled: false
